from data import ISOM2017_2, ISOM2017_2_numbers, ISSprOM2019


text = {'Dansk':
        {'Symbol names':
         {ISOM2017_2:
          {101.1: 'Højdekurve',
           101.2: 'Højdekurve, høj',
           101.3: 'Højdekurve, lavning',
           102: 'Tællekurve',
           103.1: 'Hjælpekurve',
           103.2: 'Hjælpekurve, høj',
           103.3: 'Hjælpekurve, lavning',
           104: 'Jordskrænt',
           105: 'Jorddige',
           106: 'Sammenfaldet jorddige',
           107: 'Rende',
           108: 'Lille rende',
           109: 'Punkthøj',
           110: 'Aflang punkthøj',
           111: 'Lille lavning',
           112: 'Hul',
           113: 'Ujævnt terræn',
           114: 'Meget ujævnt terræn',
           115: 'Speciel terrængenstand',
           201: 'Impassabel klippe',
           202: 'Klippeskrænt',
           203: 'Hul i klippe, hule, grotte',
           204: 'Sten',
           205: 'Stor sten',
           206: 'Klippeblok',
           207: 'Gruppe af sten',
           208: 'Blokmark',
           209: 'Tæt blokmark',
           210: 'Stenet grund, langsomt gennemløbelig',
           211: 'Stenet grund, svært gennemløbelig',
           212: 'Stenet grund, svært gennemtrængelig',
           213: 'Nøgen sandflade',
           214: 'Nøgen klippeflade',
           215: 'Skyttegrav',
           301: 'Sø',
           302: 'Lavvandet sø',
           303: 'Vandhul',
           304: 'Bred grøft, vandløb',
           305: 'Grøft, vandløb',
           306: 'Lille grøft, vandløb',
           307: 'Impassabel mose',
           308: 'Mose',
           309: 'Smal mose',
           310: 'Blød bund',
           311: 'Brønd, springvand eller vandtank',
           312: 'Kilde',
           313: 'Tydeligt vandobjekt',
           401: 'Åbent område',
           402.1: 'Åbent område med spredte træer',
           402.2: 'Åbent område med spredte buske',
           403: 'Åbent område med lav undervegetation',
           404.1: 'Åbent område med lav undervegetation og spredte træer',
           404.2: 'Åbent område med lav undervegetation og spredte buske',
           405: 'Let gennemløbelig skov',
           406: 'Langsomt gennemløbelig skov',
           407: 'Langsomt gennemløbelig underskov, god sigt',
           408: 'Svært gennemløbelig skov vist med bedre gennemløbsretning',
           409: 'Svært gennemløbelig underskov, god sigt',
           410: 'Svært gennemtrængelig skov',
           412: 'Dyrket område',
           413: 'Frugtplantage',
           414: 'Vingård eller lignende',
           415: 'Markant dyrkningsgrænse',
           416: 'Markant bevoksningsgrænse',
           417: 'Markant stort træ',
           418: 'Tydelig busk eller træ',
           419: 'Tydeligt vegetationsobject',
           501: 'Område med fast overflade',
           502: 'Bred vej',
           503: 'Vej',
           504: 'Mindre vej',
           505: 'God sti, skovvej',
           506: 'Sti',
           507: 'Utydelig sti',
           508: 'Smal lineært spor gennem terrænnet',
           509: 'Jernbane',
           510: 'Højspændingsledning, svævebane eller skilift',
           511: 'Hovedhøjspændingsledning',
           512: 'Bro/tunnel',
           513: 'Stendige',
           514: 'Sammenfaldet stendige',
           515: 'Høj mur',
           516: 'Hegn',
           517: 'Sammenfaldet hegn',
           518: 'Højt hegn',
           519: 'Gennemgang',
           520: 'Forbudt område',
           521: 'Bygning',
           522: 'Halvtag',
           523: 'Ruin',
           524: 'Højt tårn',
           525: 'Lille tårn',
           526: 'Mindesten',
           527: 'Fodersted',
           528: 'Tydeligt, lineært objekt',
           529: 'Tydeligt, impassabelt, lineært objekt',
           530: 'Tydeligt menneskabt punktobjekt',
           531: 'Tydeligt menneskabt punktobjekt',
           601: 'Magnetisk nordlinje (meridian)',
           602: 'Registerkryds (pasmærke)',
           # 603: 'Højdepunkt',
           701: 'Start',
           702: 'Kortudlevering',
           703: 'Poster',
           704: 'Postnummer',
           705: 'Linje',
           706: 'Mål',
           707: 'Markeret rute',
           708: 'Passage forbud',
           709: 'Forbudt område',
           710: 'Gennemgang',
           711: 'Forbudt rute',
           712: 'Førstehjælpspost',
           713: 'Væskeplacering',
           },
          ISSprOM2019:
          {101.1: 'Højdekurve',
           101.2: 'Højdekurve, høj',
           101.3: 'Højdekurve, lavning',
           102: 'Tællekurve',
           103.1: 'Hjælpekurve',
           103.2: 'Hjælpekurve, høj',
           103.3: 'Hjælpekurve, lavning',
           104: 'Jordskrænt',
           105: 'Jorddige',
           107: 'Rende',
           108: 'Lille rende',
           109: 'Punkthøj',
           110: 'Aflang punkthøj',
           111: 'Lille lavning',
           112: 'Hul',
           113: 'Ujævnt terræn',
           114: 'Meget ujævnt terræn',
           115: 'Speciel terrængenstand',
           201: 'Impassabel klippe',
           202: 'Klippeskrænt',
           203: 'Hul i klippe, hule, grotte',
           204: 'Sten',
           205: 'Stor sten',
           206: 'Klippeblok',
           207: 'Gruppe af sten',
           208: 'Blokmark',
           209: 'Tæt blokmark',
           210: 'Stenet grund, langsomt gennemløbelig',
           211: 'Stenet grund, svært gennemløbelig',
           212: 'Stenet grund, svært gennemtrængelig',
           213: 'Nøgen sandflade',
           214: 'Nøgen klippeflade',
           215: 'Skyttegrav',
           301: 'Sø',
           302: 'Lavvandet sø',
           303: 'Vandhul',
           304: 'Bred grøft, vandløb',
           305: 'Grøft, vandløb',
           306: 'Lille grøft, vandløb',
           307: 'Impassabel mose',
           308: 'Mose',
           309: 'Smal mose',
           310: 'Blød bund',
           311: 'Brønd, springvand eller vandtank',
           312: 'Kilde',
           313: 'Tydeligt vandobjekt',
           401: 'Åbent område',
           402.1: 'Åbent område med spredte træer',
           402.2: 'Åbent område med spredte buske',
           403: 'Åbent område med lav undervegetation',
           404.1: 'Åbent område med lav undervegetation og spredte træer',
           404.2: 'Åbent område med lav undervegetation og spredte buske',
           405: 'Let gennemløbelig skov',
           406: 'Langsomt gennemløbelig skov',
           407: 'Langsomt gennemløbelig underskov, god sigt',
           408: 'Svært gennemløbelig skov vist med bedre gennemløbsretning',
           409: 'Svært gennemløbelig underskov, god sigt',
           410: 'Svært gennemtrængelig skov',
           412: 'Dyrket område',
           413: 'Frugtplantage',
           414: 'Vingård eller lignende',
           415: 'Markant dyrkningsgrænse',
           416: 'Markant bevoksningsgrænse',
           417: 'Markant stort træ',
           418: 'Tydelig busk eller træ',
           419: 'Tydeligt vegetationsobject',
           501: 'Område med fast overflade',
           502: 'Bred vej',
           503: 'Vej',
           504: 'Mindre vej',
           505: 'God sti, skovvej',
           506: 'Sti',
           507: 'Utydelig sti',
           508: 'Smal lineært spor gennem terrænnet',
           509: 'Jernbane',
           510: 'Højspændingsledning, svævebane eller skilift',
           511: 'Hovedhøjspændingsledning',
           512: 'Bro/tunnel',
           513: 'Stendige',
           514: 'Sammenfaldet stendige',
           515: 'Høj mur',
           516: 'Hegn',
           517: 'Sammenfaldet hegn',
           518: 'Højt hegn',
           519: 'Gennemgang',
           520: 'Forbudt område',
           521: 'Bygning',
           522: 'Halvtag',
           523: 'Ruin',
           524: 'Højt tårn',
           525: 'Lille tårn',
           526: 'Mindesten',
           527: 'Fodersted',
           528: 'Tydeligt, lineært objekt',
           529: 'Tydeligt, impassabelt, lineært objekt',
           530: 'Tydeligt menneskabt punktobjekt',
           531: 'Tydeligt menneskabt punktobjekt',
           601: 'Magnetisk nordlinje (meridian)',
           602: 'Registerkryds (pasmærke)',
           # 603: 'Højdepunkt',
           701: 'Start',
           702: 'Kortudlevering',
           703: 'Poster',
           704: 'Postnummer',
           705: 'Linje',
           706: 'Mål',
           707: 'Markeret rute',
           708: 'Passage forbud',
           709: 'Forbudt område',
           710: 'Gennemgang',
           711: 'Forbudt rute',
           712: 'Førstehjælpspost',
           713: 'Væskeplacering',
           },

          },
         'Categories': {ISOM2017_2:
                        {'Alle': ISOM2017_2_numbers,
                            'Terrænformer': [n for n in ISOM2017_2_numbers if n // 100 == 1],

                         'Klipper og stenblokke': [n for n in ISOM2017_2_numbers if n // 100 == 2],
                         'Vand og mose': [n for n in ISOM2017_2_numbers if n // 100 == 3],
                         'Vegetation': [n for n in ISOM2017_2_numbers if n // 100 == 4],
                         'Anlagte terrængenstande': [n for n in ISOM2017_2_numbers if n // 100 == 5],
                         'Tekniske symboler': [n for n in ISOM2017_2_numbers if n // 100 == 6],
                         'Banesymboler': [n for n in ISOM2017_2_numbers if n // 100 == 7]
                         }

                        },
         'app_text': {'Next': 'Næste',
                      }
         }

        }
